.\" This is a comment
.\" Contact @yokofakun
.TH verticalize 1 "01 July 2019" ".1" "Verticalize delimited files"
.SH NAME
verticalize2graph \- Verticalize delimited files
.SH SYNOPSIS
verticalize (options) (file|stdin)
.SH DESCRIPTION
Verticalize delimited text files
.SH OPTIONS
.TP
.B \-\^n 
first line is NOT header
.TP
.B \-\^d 
(char) delimiter (default : tabulation)
.SH SEE ALSO
head(1), tail(1)
.SH AUTHOR
Pierre Lindenbaum (@yokofakun)
